const mangas = [
    {
        id: 1,
        titulo: "One Piece",
        descricao: "A jornada épica de Monkey D. Luffy e sua tripulação enquanto exploram os mares em busca do tesouro supremo.",
        autor: "Eiichiro Oda",
        capitulos: 1100,
        nota: "9.5",
        ano: 1997,
        img: "./assets/images/one-piece.jpg",
        genero: "Shounen",
        statusManga: "Em andamento",
        statusLeitura: "Lendo",
    },
    {
        id: 2,
        titulo: "Death Note",
        descricao: "Um estudante encontra um caderno sobrenatural que permite matar qualquer pessoa cujo nome seja escrito nele.",
        autor: "Tsugumi Ohba",
        capitulos: 108,
        nota: "9.0",
        ano: 2003,
        img: "./assets/images/death-note.jpg",
        genero: "Mistério",
        statusManga: "Finalizado",
        statusLeitura: "Lido",
        marcador: "Favorito"
    },
    {
        id: 4,
        titulo: "Chainsaw Man",
        descricao: "Denji funde sua alma com seu cão-demônio para se tornar um caçador de demônios impiedoso.",
        autor: "Tatsuki Fujimoto",
        capitulos: 150,
        nota: "8.7",
        ano: 2018,
        img: "./assets/images/chainsaw-man.png",
        genero: "Ação",
        statusManga: "Em andamento",
        statusLeitura: "Lendo",
    },
    {
        id: 5,
        titulo: "Jujutsu Kaisen",
        descricao: "Yuji Itadori entra no mundo das maldições após consumir um objeto amaldiçoado poderoso.",
        autor: "Gege Akutami",
        capitulos: 250,
        nota: "8.9",
        ano: 2018,
        img: "./assets/images/jujutsu-kaisen.jpg",
        genero: "Sobrenatural",
        statusManga: "Em andamento",
        statusLeitura: "Lido",
    },
    {
        id: 6,
        titulo: "Vagabond",
        descricao: "A vida fictícia do lendário espadachim Miyamoto Musashi e sua busca pelo verdadeiro caminho da espada.",
        autor: "Takehiko Inoue",
        capitulos: 327,
        nota: "9.6",
        ano: 1998,
        img: "./assets/images/vagabond.png",
        genero: "Seinen",
        statusManga: "Hiato",
        statusLeitura: "Lido",
        marcador: "Favorito"
    },
    {
        id: 7,
        titulo: "Vinland Saga",
        descricao: "Thorfinn busca vingança contra o assassino de seu pai em uma jornada épica durante as invasões vikings.",
        autor: "Makoto Yukimura",
        capitulos: 200,
        nota: "9.4",
        ano: 2005,
        img: "./assets/images/vinland-saga.jpg",
        genero: "Seinen",
        statusManga: "Em andamento",
        statusLeitura: "Lendo",
    },
    {
        id: 3,
        titulo: "Blue Lock",
        descricao: "Após o desastre na Copa do Mundo, o Japão cria um projeto para treinar o atacante mais egoísta do mundo.",
        autor: "Muneyuki Kaneshiro",
        capitulos: 250,
        nota: "8.8",
        ano: 2018,
        img: "./assets/images/blue-lock.jpg",
        genero: "Esporte",
        statusManga: "Em andamento",
        statusLeitura: "Lendo",
    },
    {
        id: 8,
        titulo: "Solo Leveling",
        descricao: "O caçador mais fraco de todos recebe um poder misterioso que o permite subir de nível como em um jogo.",
        autor: "Chugong",
        capitulos: 179,
        nota: "9.1",
        ano: 2018,
        img: "./assets/images/solo-leveling.png",
        genero: "Aventura",
        statusManga: "Finalizado",
        statusLeitura: "Lido",
    },
    {
        id: 10,
        titulo: "Fullmetal Alchemist",
        descricao: "Dois irmãos usam a alquimia em uma busca para recuperar seus corpos após um experimento proibido.",
        autor: "Hiromu Arakawa",
        capitulos: 108,
        nota: "9.2",
        ano: 2001,
        img: "./assets/images/fullmetal.png",
        genero: "Shounen",
        statusManga: "Finalizado",
        statusLeitura: "Lido",
    },
    {
        id: 11,
        titulo: "Spy x Family",
        descricao: "Um espião, uma assassina e uma telepata fingem ser uma família para manter a paz mundial.",
        autor: "Tatsuya Endo",
        capitulos: 95,
        nota: "8.9",
        ano: 2019,
        img: "./assets/images/spy-family.jpg",
        genero: "Comédia",
        statusManga: "Em andamento",
        statusLeitura: "Lendo",
    },
    {
        id: 12,
        titulo: "Monster",
        descricao: "Um neurocirurgião se vê envolvido em uma trama de assassinatos após salvar a vida de um menino.",
        autor: "Naoki Urasawa",
        capitulos: 162,
        nota: "9.4",
        ano: 1994,
        img: "./assets/images/monster.jpg",
        genero: "Suspense",
        statusManga: "Finalizado",
        statusLeitura: "Lido",
    },
    {
        id: 15,
        titulo: "Demon Slayer",
        descricao: "Tanjiro se torna um caçador de demônios para salvar sua irmã e vingar sua família.",
        autor: "Koyoharu Gotouge",
        capitulos: 205,
        nota: "8.6",
        ano: 2016,
        img: "./assets/images/demon-slayer.jpg",
        genero: "Ação",
        statusManga: "Finalizado",
        statusLeitura: "Lido",
        marcador: "Favorito"
    },
    {
        id: 9,
        titulo: "Berserk",
        descricao: "Guts, um guerreiro solitário, busca vingança contra aquele que o traiu em um mundo de fantasia sombria.",
        autor: "Kentaro Miura",
        capitulos: 375,
        nota: "9.8",
        ano: 1989,
        img: "./assets/images/berserk.jpg",
        genero: "Seinen",
        statusManga: "Em andamento",
        statusLeitura: "Lido",
    },
    {
        id: 17,
        titulo: "Dandadan",
        descricao: "Um nerd aficionado por alienígenas e uma garota de uma família de médiuns se envolvem em batalhas ocultas bizarras e hilárias.",
        autor: "Yukinobu Tatsu",
        capitulos: 160,
        nota: "8.8",
        ano: 2021,
        img: "./assets/images/dandadan.jpg",
        genero: "Ação/Comédia",
        statusManga: "Em lançamento",
        statusLeitura: "Lendo"
    },
    {
        id: 18,
        titulo: "Shingeki no Kyojin",
        descricao: "A humanidade luta pela sobrevivência contra gigantes devoradores de homens em uma trama de mistério político e liberdade.",
        autor: "Hajime Isayama",
        capitulos: 139,
        nota: "9.1",
        ano: 2009,
        img: "./assets/images/shingeki.jpg",
        genero: "Drama/Mistério",
        statusManga: "Finalizado",
        statusLeitura: "Favorito"
    },
    {
        id: 19,
        titulo: "86: Eighty Six",
        descricao: "Em uma guerra travada por drones, os jovens do distrito 86 lutam uma batalha invisível e desumana contra o Império.",
        autor: "Asato Asato",
        capitulos: 12,
        nota: "8.7",
        ano: 2018,
        img: "./assets/images/86-eighty-six.jpg",
        genero: "Mecha/Drama",
        statusManga: "Finalizado",
        statusLeitura: "Favorito"
    },
    {
        id: 20,
        titulo: "Hunter x Hunter",
        descricao: "Gon Freecss busca se tornar um Hunter para encontrar seu pai, enfrentando desafios que testam sua moral e força.",
        autor: "Yoshihiro Togashi",
        capitulos: 400,
        nota: "9.0",
        ano: 1998,
        img: "./assets/images/hunter-x-hunter.jpg",
        genero: "Aventura",
        statusManga: "Finalizado",
        statusLeitura: "Favorito"
    },
    {
        id: 21,
        titulo: "Re:Zero",
        descricao: "Subaru Natsuki é transportado para outro mundo onde ganha a habilidade de voltar no tempo toda vez que morre.",
        autor: "Tappei Nagatsuki",
        capitulos: 50,
        nota: "8.3",
        ano: 2014,
        img: "./assets/images/re-zero.jpg",
        genero: "Isekai/Fantasia",
        statusManga: "Em lançamento",
        statusLeitura: "Lendo"
    },
    {
        id: 22,
        titulo: "Tokyo Ghoul",
        descricao: "Kaneki se torna um meio-ghoul após um acidente e precisa aprender a sobreviver na sociedade sombria dos devoradores de carne.",
        autor: "Sui Ishida",
        capitulos: 143,
        nota: "8.5",
        ano: 2011,
        img: "./assets/images/tokyo-ghoul.png",
        genero: "Terror/Ação",
        statusManga: "Finalizado",
        statusLeitura: "Favorito"
    },
    {
        id: 23,
        titulo: "Noragami",
        descricao: "Yato é um deus menor que sonha em ter milhões de seguidores, mas sua vida muda ao conhecer a humana Hiyori.",
        autor: "Adachitoka",
        capitulos: 109,
        nota: "8.2",
        ano: 2010,
        img: "./assets/images/noragami.jpg",
        genero: "Sobrenatural",
        statusManga: "Finalizado",
        statusLeitura: "Lido"
    },
    {
        id: 24,
        titulo: "Tokyo Revengers",
        descricao: "Takemichi volta no tempo para seus dias de escola para salvar sua ex-namorada de uma gangue violenta.",
        autor: "Ken Wakui",
        capitulos: 278,
        nota: "7.9",
        ano: 2017,
        img: "./assets/images/tokyo-revengers.jpg",
        genero: "Drama/Ação",
        statusManga: "Finalizado",
        statusLeitura: "Lido"
    }
];